' Visit http://plantuml.com/de/ for more information!

' RCM-DX diagramm example and explanation at the start of specification
@startuml RCM_DX_diagram_example

  object DATASOURCE {
    a:Element = "DATASOURCE"
  }
  note left
    - Group's in
      color Yellow
    
    - Attibutes with "a:"
      at the beginning
  end note

  object timestamp #LightGray

  object CHANNEL {
    a:Element = "CHANNEL"
    a:ChannelBasis
    a:----
  }

  object data #LightGray{
    a:Unit (string)
  }
  note left
    Dataset's in
    color gray
  end note

  note as HINT
    <size:30><&warning>
    Datasets can be described
    inside a group with "d:"
     at the beginning!
  end note

  DATASOURCE "1" o-- "1" timestamp
  DATASOURCE "1" o-- "1..n" CHANNEL
  CHANNEL "1" o-- "0..n" data

@enduml

' RCM-DX Common Structure Overview
@startuml RCM_DX_Structure

  object RCMDX

  object "//SESSION_NAME//" as session_name

  object "//MEASURINGSYSTEM_NAME//" as measuringsystem_name

  object CLEARANCEINFORMATION
  object DATAPROCESSING

  object PLATFORM

  object POSITION
  object SECTION
  
  object ENVIRONMENT

  object EVENTS
  object RECORDS

  object TOPOLOGY

  RCMDX "1" o-- "1..n" session_name
  RCMDX "1" o-- "0..1" CLEARANCEINFORMATION
  RCMDX "1" o-- "0..1" DATAPROCESSING
  
  session_name "1" o-- "1" PLATFORM
  session_name "1" o-- "1" POSITION
  session_name "1" o-- "0..1" ENVIRONMENT
  session_name "1" o-- "1..n" measuringsystem_name
  session_name "1" o-- "0..1" EVENTS
  session_name "1" o-- "0..1" RECORDS
  session_name "1" o-- "1" TOPOLOGY
  session_name "1" o-- "1" SECTION
  
@enduml

' RCM-DX Measurement Structure Overview
@startuml RCM_DX_MS_overview

  object "//SESSION_NAME//" as session_name {
    a:Element (string) = "SESSION"
    a:MeasuringMode {OPERATIV | SIMULATION | TEST}
    a:StartTime (64bit integer, timestamp)
    a:EndTime (64bit integer, timestamp)
  }

  object "//MEASURINGSYSTEM_NAME//" as measuringsystem_name {
    a:Element (string) = "MEASURINGSYSTEM"
    a:Family (string)
    a:Revision (string)
    a:InstanceVersion (string)
    a:MeasuringMode (string)
  }

  object "//DATASOURCE_NAME//" as datasource_name {
    a:Element (string) = "DATASOURCE"
  }

  object LIMIT

  object "//LIMIT_NAME//" as limit_name {
    a:Priority (8bit integer)
    a:LimitBound (string)
  }

  object "//CHANNEL_NAME//" as channel_name {
    a:Element (string) = "CHANNEL"
    a:ChannelType (string)
    a:TriggerMode (string)
    a:CommonTriggerFrequency (32bit float)
    a:CommonTriggerDistance (32bit float)
    a:ChannelBasis (string)
    a:Neighbor (string)
    a:MeasurementUncertinty (32bit float)
    a:PositionOffset (32bit float)
  }

  object VID {
    a:ContentType (MIME-Type, string)
    a:DataTyp (string)
    a:FramesPerSecond (16bit signed integer)
    a:ResolutionX (32bit signed integer)
    a:ResolutionY (32bit signed integer)
  }

  object IMG {
    a:ContentType (MIME-Type, string)
    a:DataTyp (string)
    a:ResolutionType (string)
    a:ResolutionX (32bit signed integer)
    a:ResolutionY (32bit signed integer)
  }

  object data #LightGray {
    a:Unit (string)
  }

  object data.PRE.MIN.X #LightGray {
    a:Unit (string)
  }

  object data.PRE.MAX.X #LightGray {
    a:Unit (string)
  }

  object data.PRE.AVG.X #LightGray {
    a:Unit (string)
  }

  object img.NNNNNNNNN #LightGray
  object vid.NNNNNNNNN #LightGray

  object timeindex #LightGray {
    a:BlockSize (long)
    a:Exponent (integer)
    a:Depth (integer)
  }
  
  object timestamp #LightGray
  object "timestamp" as ti #LightGray
  object duration #LightGray
  object "duration" as du #LightGray
  
  object sampleindex #LightGray {
    a:Sorted (string)
    **TBD:** Ist dieses Attribut notwendig?
  }

  object limitvalue #LightGray

  object coord.CN #LightGray {
    a:Unit (string)
  }

  session_name "1" o-- "1..n" measuringsystem_name

  measuringsystem_name "1" o-- "1..n" datasource_name
  datasource_name "1" o-- "1" ti
  datasource_name "1" o-- "0..1" du
  datasource_name "1" o-- "0..1" timeindex
  datasource_name "1" o-- "1..n" channel_name

  channel_name "1" o-- "0..1" data
  channel_name "1" o-- "0..1" sampleindex
  channel_name "1" o-- "0..n" coord.CN
  channel_name "1" o-- "0..n" data.PRE.MIN.X
  channel_name "1" o-- "0..n" data.PRE.MAX.X
  channel_name "1" o-- "0..n" data.PRE.AVG.X

  channel_name "1" o-- "0..1" VID
  channel_name "1" o-- "0..1" IMG

  channel_name "1" o-- "0..1" LIMIT

  LIMIT "1" o-- "1" limit_name

  limit_name "1" o-- "1" timestamp
  limit_name "1" o-- "1" duration
  limit_name "1" o-- "1" limitvalue

  IMG "1" o-- "1..n" img.NNNNNNNNN
  VID "1" o-- "1..n" vid.NNNNNNNNN

@enduml

' RCM-DX Topology Structure Overview
@startuml RCM_DX_Topology_overview

  object "//SESSION_NAME//" as session_name {
    a:Element (string) = "SESSION"
    a:MeasuringMode {OPERATIV | SIMULATION | TEST}
    a:StartTime (64bit integer, timestamp)
    a:EndTime (64bit integer, timestamp)
  }

  object TOPOLOGY {
    a:Version (string)
  }

  object TRACK {
    d:id (32bit signed integer)
    d:direction (8bit signed integer)
    d:gtgId (string)
    d:length (32bit float)
    d:name (string)
    d:nrLine (string)
    d:pointFrom (32bit signed integer)
    d:pointTo (32bit signed integer)
    d:switchType (8bit signed integer)
    d:trackType (8bit signed integer)
  }

  object LINE {
    d:id (32bit signed integer)
    d:name (string)
    d:firstStation (string)
    d:lastStation (string)
    d:fromKilometer (32bit float)
    d:toKilometer (32bit float)
  }

  object SWITCHTRACK {
    d:gleisstrangId (32bit signed integer)
    d:gleisstrangBez (string)
    d:weicheId (32bit signed integer)
    d:ablenkRichtung (string)
    d:ablenkung (string)
    d:betriebspunkt (string)
    d:herzStueck (string)
    d:minRadius  (32bit float)
    d:nr (32bit signed integer)
    d:zusNr (string)
    d:schienenProfil
    d:status (string)
    d:schienenProfil (string)
    d:schwellenArt (string)
    d:typenPlanNr (32bit signed integer)
    d:typNrZusatz (string)
    d:weichenArt (string)
    d:weichenTyp (string)
    d:weichenForm (string)
    d:weichenZunge (string)
  }

  object TRACKOBJECT {
    d:trackId (32bit signed integer)
    d:type (32bit signed integer)
    d:positionStart (32bit float)
    d:positionEnd (32bit float)
    d:extraInfo (string)
  }

  object TRACKPOINT {
    d:trackId (32bit signed integer)
    d:lineId (32bit signed integer)
    d:x (32bit float)
    d:y (32bit float)
    d:z (32bit float)
    d:radius (32bit float)
    d:kilometer (32bit float)
    d:position (32bit float)
    d:cant (32bit float)
    d:inclination (32bit float)
  }

  object PROPERTY {
    d:propertyId (32bit signed integer)
    d:name (string)
    d:description.ge (string)
    d:description.fr (string)
    d:description.it (string)
    d:description.en (string)
  }

  session_name "1" o-- "1" TOPOLOGY

  TOPOLOGY "1" o-- "1" TRACK
  TOPOLOGY "1" o-- "1" LINE
  TOPOLOGY "1" o-- "1" SWITCHTRACK
  TOPOLOGY "1" o-- "1" TRACKOBJECT
  TOPOLOGY "1" o-- "1" TRACKPOINT
  TOPOLOGY "1" o-- "1" PROPERTY

@enduml

' RCM-DX Platform Structure Overview
@startuml RCM_DX_Platform_overview

  object "//SESSION_NAME//" as session_name {
    a:Element (string) = "SESSION"
    a:MeasuringMode {OPERATIV | SIMULATION | TEST}
    a:StartTime (64bit integer, timestamp)
    a:EndTime (64bit integer, timestamp)
  }

  object PLATFORM {
    a:Name (string)
    a:VehicleNumber (string)
  }

  object CONFIGURATION
  object global #LightGray
  object network #LightGray

  session_name "1" o-- "1" PLATFORM
  PLATFORM "1" o-- "1" CONFIGURATION
  CONFIGURATION "1" o-- "1" global
  CONFIGURATION "1" o-- "1" network

@enduml

' RCM-DX Environment Structure Overview
@startuml RCM_DX_Environment_overview

  object "//SESSION_NAME//" as session_name {
    a:Element (string) = "SESSION"
    a:MeasuringMode {OPERATIV | SIMULATION | TEST}
    a:StartTime (64bit integer, timestamp)
    a:EndTime (64bit integer, timestamp)
  }

  object ENVIRONMENT 

  object timestamp #LightGray

  object VEHICLESPEED {
    d:data (64bit integer)
  }

  object AMBIENTTEMPERATURE {
    d:data (64bit integer)
  }

  object WINDSPEED {
    d:data (64bit integer)
  }

  object WINDDIRECTION {
    d:data (64bit integer)
  }

  object WEATHERCONDITIONS {
    d:data (64bit integer)
  }

  session_name "1" o-- "0..1" ENVIRONMENT
  ENVIRONMENT "1" o-- "1" VEHICLESPEED
  ENVIRONMENT "1" o-- "1" AMBIENTTEMPERATURE
  ENVIRONMENT "1" o-- "1" WINDSPEED
  ENVIRONMENT "1" o-- "1" WINDDIRECTION
  ENVIRONMENT "1" o-- "1" WEATHERCONDITIONS
  ENVIRONMENT "1" o-- "1" timestamp

@enduml

' RCM-DX Logging Structure Overview
@startuml RCM_DX_Logging_overview

  object "//MEASURINGSYSTEM_NAME//" as measuringsystem_name {
    a:Element (string) = "MEASURINGSYSTEM"
    a:Family (string)
    a:Revision (string)
    a:InstanceVersion (string)
    a:MeasuringMode (string)
  }

  object LOGGING

  object MESSAGES {
    d:message (string)
    d:level (string)
    d:systemReference (string)
    d:channelReference (string)
    d:timestamp (64bit integer, timestamp)
  }

  object OUTAGES {
    d:message (string)
    d:level (string)
    d:systemReference (string)
    d:channelReference (string)
    d:timestamp (64bit integer, timestamp)
    d:durations (64bit integer)
  }

  measuringsystem_name "1" o-- "0..1" LOGGING

  LOGGING "1" o-- "1" MESSAGES
  LOGGING "1" o-- "1" OUTAGES

@enduml

@startuml Limit_overview

  object LIMIT

  object "//CHANNEL_NAME//" as channel_name

  object data #LightGray
  object timestamp #LightGray
  object duration #LightGray
  object limitvalue #LightGray

  object "//LIMIT_NAME//" as limit_name {
    a:Priority (8bit integer)
    a:LimitBound (string)
  }

  channel_name "1" o-- "1" data
  channel_name "1" o-- "0..1" LIMIT
  LIMIT "1" o-- "1..n" limit_name
  limit_name "1" o-- "1" timestamp
  limit_name "1" o-- "1" duration
  limit_name "1" o-- "1..n" limitvalue

@enduml

' RCM-DX binary tree
@startuml binaryTree

  storage 64 #Red
  storage 32
  storage 16
  storage 8
  storage 24
  storage 48
  storage 96
  storage 80
  storage 112
  storage 72
  storage 88
  storage 104
  storage 120
  storage 40
  storage 56

  64 -- 32
  64 -- 96
  96 -- 80
  96 -- 112
  80 -- 72
  80 -- 88
  112 -- 104
  112 -- 120
  32 -- 16
  32 -- 48
  16 -- 8
  16 -- 24
  48 -- 40
  48 -- 56

@enduml