@startuml RCM_DX_Structure

  object RCMDX

  object data.PRE.MIN.X #LightGray {
    a:Unit (string)
  }

  object data.PRE.MAX.X #LightGray {
    a:Unit (string)
  }

  object data.PRE.AVG.X #LightGray {
    a:Unit (string)
  }

  object LIMIT

  object "//LIMIT_NAME//" as limit_name {
    a:Priority (8bit integer)
    a:LimitBound (string)
  }

  object "//SESSION_NAME//" as session_name {
    a:Element (string) = "SESSION"
    a:MeasuringMode {OPERATIV | SIMULATION | TEST}
    a:StartTime (64bit integer, timestamp)
    a:EndTime (64bit integer, timestamp)
  }

  object ENVIRONMENT

  object VEHICLESPEED {
    d:data (64bit integer)
  }

  object AMBIENTTEMPERATURE {
    d:data (64bit integer)
  }

  object WINDSPEED {
    d:data (64bit integer)
  }

  object WINDDIRECTION {
    d:data (64bit integer)
  }

  object WEATHERCONDITIONS {
    d:data (64bit integer)
  }
  
  object TOPOLOGY {
    a:Version (string)
  }

  object TRACKS {
    d:id (32bit signed integer)
    d:direction (8bit signed integer)
    d:gtgId (string)
    d:length (32bit float)
    d:name (string)
    d:nrLine (string)
    d:pointFrom (32bit signed integer)
    d:pointTo (32bit signed integer)
    d:switchType (8bit signed integer)
    d:trackType (8bit signed integer)
  }

  object LINES {
    d:id (32bit signed integer)
    d:name (string)
    d:firstStation (string)
    d:lastStation (string)
    d:fromKilometer (32bit float)
    d:toKilometer (32bit float)
  }

  object SWITCHTRACKS {
    d:gleisstrangId (32bit signed integer)
    d:gleisstrangBez (string)
    d:weicheId (32bit signed integer)
    d:ablenkRichtung (string)
    d:ablenkung (string)
    d:betriebspunkt (string)
    d:herzStueck (string)
    d:minRadius  (32bit float)
    d:nr (32bit signed integer)
    d:zusNr (string)
    d:schienenProfil
    d:status (string)
    d:schienenProfil (string)
    d:schwellenArt (string)
    d:typenPlanNr (32bit signed integer)
    d:typNrZusatz (string)
    d:weichenArt (string)
    d:weichenTyp (string)
    d:weichenForm (string)
    d:weichenZunge (string)
  }

  object TRACKOBJECTS {
    d:trackId (32bit signed integer)
    d:type (32bit signed integer)
    d:positionStart (32bit float)
    d:positionEnd (32bit float)
    d:extraInfo (string)
  }

  object TRACKPOINTS {
    d:trackId (32bit signed integer)
    d:lineId (32bit signed integer)
    d:x (32bit float)
    d:y (32bit float)
    d:z (32bit float)
    d:radius (32bit float)
    d:kilometer (32bit float)
    d:position (32bit float)
    d:cant (32bit float)
    d:inclination (32bit float)
  }

  object PROPERTIES {
    d:propertyId (32bit signed integer)
    d:name (string)
    d:description.ge (string)
    d:description.fr (string)
    d:description.it (string)
    d:description.en (string)
  }

  object "//MEASURINGSYSTEM_NAME//" as measuringsystem_name {
    a:Element (string) = "MEASURINGSYSTEM"
    a:Family (string)
    a:Revision (string)
    a:InstanceVersion (string)
    a:MeasuringMode (string)
  }

  object "//DATASOURCE_NAME//" as datasource_name {
    a:Element (string) = "DATASOURCE"
  }

  object "//CHANNEL_NAME//" as channel_name {
    a:Element (string) = "CHANNEL"
    a:ChannelType (string)
    a:TriggerMode (string)
    a:CommonTriggerFrequency (32bit float)
    a:CommonTriggerDistance (32bit float)
    a:ChannelBasis (string)
    a:Neighbor (string)
    a:MeasurementUncertinty (32bit float)
    a:PositionOffset (32bit float)
  }

  object VID {
    a:ContentType (MIME-Type, string)
    a:DataTyp (string)
    a:FramesPerSecond (16bit signed integer)
    a:ResolutionX (32bit signed integer)
    a:ResolutionY (32bit signed integer)
  }

  object IMG {
    a:ContentType (MIME-Type, string)
    a:DataTyp (string)
    a:ResolutionType (string)
    a:ResolutionX (32bit signed integer)
    a:ResolutionY (32bit signed integer)
  }
  
  object PLATFORM {
    a:Name (string)
    a:VehicleNumber (string)
  }

  object LOGGING

  object MESSAGES {
    d:message (string)
    d:level (string)
    d:systemReference (string)
    d:channelReference (string)
    d:timestamp (64bit integer, timestamp)
  }

  object OUTAGES {
    d:message (string)
    d:level (string)
    d:systemReference (string)
    d:channelReference (string)
    d:timestamp (64bit integer, timestamp)
    d:durations (64bit integer)
  }

  object "//LIMIT_NAME//" as limit_name #LightGray {
    a:Element (string) = "LIMIT"
  }

  object CONFIGURATION
  object "CONFIGURATION" as c1

  object global #LightGray
  object network #LightGray

  object img.NNNNNNNNN #LightGray
  object vid.NNNNNNNNN #LightGray

  object "timestamp" as t1 #LightGray
  object "timestamp" as t2 #LightGray
  object "timestamp" as t3 #LightGray
  object "timestamp" as t4 #LightGray
  object "duration" as d1 #LightGray
  object "duration" as d2 #LightGray

  object limitvalue #LightGray
  
  object sampleindex #LightGray {
    a:Sorted (string)
    **TBD:** Ist dieses Attribut notwendig?
  }
  
  object coord.CN #LightGray {
    a:Unit
  }

  object "//SETTING_NAME//" as setting_name {
    a:Element (string) = "SETTING"
  }
  
  object setting #LightGray
  
  object data #LightGray {
    a:Unit
  }

  RCMDX "1" o-- "1" PLATFORM

  channel_name "1" o-- "0..n" data
  channel_name "1" o-- "1" LIMIT
  LIMIT "1" o-- "1..n" limit_name
  limit_name "1" o-- "1" t1
  limit_name "1" o-- "1" d1
  limit_name "1" o-- "1" limitvalue

  session_name "1" o-- "1" ENVIRONMENT
  ENVIRONMENT "1" o-- "1" t3
  ENVIRONMENT "1" o-- "1" VEHICLESPEED
  ENVIRONMENT "1" o-- "1" AMBIENTTEMPERATURE
  ENVIRONMENT "1" o-- "1" WINDSPEED
  ENVIRONMENT "1" o-- "1" WINDDIRECTION
  ENVIRONMENT "1" o-- "1" WEATHERCONDITIONS
  
  PLATFORM "1" o-- "1" session_name
  PLATFORM "1" o-- "1" CONFIGURATION
  CONFIGURATION "1" o-- "1" global
  CONFIGURATION "1" o-- "1" network

  session_name "1" o-- "1..n" measuringsystem_name

  measuringsystem_name "1" o-- "1..n" datasource_name
  datasource_name "1" o-- "1" t2
  datasource_name "1" o-- "0..1" d2

  datasource_name "1" o-- "1..n" channel_name

  channel_name "1" o-- "0..1" sampleindex
  channel_name "1" o-- "0..n" coord.CN

  channel_name "1" o-- "0..1" VID
  channel_name "1" o-- "0..1" IMG

  IMG "1" o-- "1..n" img.NNNNNNNNN
  VID "1" o-- "1..n" vid.NNNNNNNNN

  session_name "1" o-- "1" TOPOLOGY

  TOPOLOGY "1" o-- "1" TRACKS
  TOPOLOGY "1" o-- "1" LINES
  TOPOLOGY "1" o-- "1" SWITCHTRACKS
  TOPOLOGY "1" o-- "1" TRACKOBJECTS
  TOPOLOGY "1" o-- "1" TRACKPOINTS
  TOPOLOGY "1" o-- "1" PROPERTIES

  channel_name "1" o-- "0..n" data.PRE.MIN.X
  channel_name "1" o-- "0..n" data.PRE.MAX.X
  channel_name "1" o-- "0..n" data.PRE.AVG.X

  measuringsystem_name "1" o-- "1" LOGGING

  LOGGING "1" o-- "1" MESSAGES
  LOGGING "1" o-- "1" OUTAGES

  measuringsystem_name "1" o-- "1" c1
  c1 "1" o-- "1..n" setting_name
  setting_name "1" o-- "1" setting
  setting_name "1" o-- "1" t4
  
@enduml