' Visit http://plantuml.com/de/ for more information!

' RCM-DX diagramm example and explanation at the start of specification
@startuml rcmdx_diagram_example

  object "//DATASOURCE_NAME//" as DATASOURCE {
    a:Element (string) = "DATASOURCE"
  }
  note left
    - Group's in
      color Yellow
    
    - Attibutes with "a:"
      at the beginning

    - Datasets with "d:"
      at the beginning
  end note

  object timestamp #LightGray

  object "//CHANNEL_NAME//" as channel {
    a:Element = "CHANNEL"
    a:ChannelBasis
    a:----
  }

  object data #LightGray{
    a:Unit (string)
  }
  note left
    Data sets can also
    be individually in 
    the color gray.
  end note

  DATASOURCE "1" o-- "1" timestamp
  DATASOURCE "1" o-- "1..n" channel
  channel "1" o-- "0" data

@enduml

@startuml rcmdx_root_group

  object RCMDX {
    a:Major (16 bit integer)
    a:Minor (16 bit integer)
  }
  
  object PLATFORM {
    a:Name (Enum)
    a:VehicleNumber (string)
  }

  RCMDX "1" o-- "1" PLATFORM

  object DATAPROCESSING {
    d:key (string)
    d:value (string)
  }
  RCMDX "1" o-- "1" DATAPROCESSING

  object CLEARANCEINFORMATION {
    d:key (string)
    d:value (string)
  }
  RCMDX "1" o-- "1" CLEARANCEINFORMATION

@enduml

@startuml rcmdx_platform_group

  object PLATFORM {
    a:Name (Enum)
    a:VehicleNumber (string)
  }

  object "CONFIGURATION" as platform_config {
    d:global (string)
    d:network (string)
  }

  PLATFORM "1" o-- "1" platform_config

  object "//SESSION_NAME//" as session_name {
    a:Element (string) = "SESSION"
    a:StartTime (Timestamp)
    a:EndTime (Timestamp)
    a:PositionSource (string)
  }

  PLATFORM "1" o-- "1" session_name

@enduml

@startuml rcmdx_session_group

  object "//SESSION_NAME//" as session_name {
    a:Element (string) = "SESSION"
    a:StartTime (Timestamp)
    a:EndTime (Timestamp)
    a:PositionSource (string)
  } 
  note left: Naming pattern: YYYYMMDD_hhmmss.SSS

  object RECORD {
    ...
  }
  session_name "1" o-- "0..1" RECORD

  object EVENT {
    ...
  }
  session_name "1" o-- "0..1" EVENT

  object TOPOLOGY {
    ...
  }
  session_name "1" o-- "1" TOPOLOGY

  object "//MEASURINGSYSTEM_NAME//" as MEASURINGSYSTEM {
    ...
  }
  session_name "1" o-- "1..n" MEASURINGSYSTEM

  object ENVIRONMENT {
    ...
  }
  session_name "1" o-- "0..1" ENVIRONMENT

  object POSITION {
    ...
  }
  session_name "1" o-- "1" POSITION

  object SECTION {
    ...
  }
  session_name "1" o-- "1" SECTION
@enduml

@startuml rcmdx_section_group

  object SECTION

    object SECTIONINFO {
    d:firstTrackOffset (64 bit float)
    d:lastTrackOffset (64 bit float)
    d:startTimestamp (Timestamp)
    d:endTimestamp (Timestamp)
    d:coachOrientation (Enum)
    d:trackInfoOffset (64 bit float)
  }
  SECTION "1" o-- "1" SECTIONINFO

  object TRACKLIST {
    d:id (32 bit signed integer)
    d:startTimestamp (Timestamp)
    d:endTimestamp (Timestamp)
    d:orientation (Enum)
    d:startCoveredDistance (64 bit float)
    d:endCoveredDistance (64 bit float)
  }
  SECTION "1" o-- "1" TRACKLIST

@enduml

@startuml rcmdx_environment_group

  object ENVIRONMENT

  object "timestamp" as env_timestamp #LightGray {
    data type: Timestamp
  }
  ENVIRONMENT "1" o-- "1" env_timestamp

  object VEHICLESPEED {
    a:Unit (meters per second [m/s])
    d:data (16 bit float)
  }
  ENVIRONMENT "1" o-- "0..1" VEHICLESPEED

  object AMBIENTTEMPERATURE {
    a:Unit (degrees celsius [°C])
    d:data (16 bit float)
  }
  ENVIRONMENT "1" o-- "0..1" AMBIENTTEMPERATURE

  object WINDSPEED {
    a:Unit (meters per second [m/s])
    d:data (16 bit float)
  }
  ENVIRONMENT "1" o-- "0..1" WINDSPEED

  object WINDDIRECTION {
    a:Unit (degree [°])
    d:data (16 bit float)
  }
  ENVIRONMENT "1" o-- "0..1" WINDDIRECTION

  object WEATHERCONDITIONS {
    a:Unit (string)
    d:data (64 bit integer)
  }
  ENVIRONMENT "1" o-- "0..1" WEATHERCONDITIONS

@enduml

@startuml rcmdx_topology_group
  object TOPOLOGY {
    a:Version (string)
  }

  object TRACKS {
    ...
  }
  TOPOLOGY "1" o-- "1" TRACKS

  object SWITCHTRACKS {
    ...
  }
  TOPOLOGY "1" o-- "1" SWITCHTRACKS

  object TRACKOBJECTS {
    ...
  }
  TOPOLOGY "1" o-- "1" TRACKOBJECTS

  object TRACKPOINTS {
    ...
  }
  TOPOLOGY "1" o-- "1" TRACKPOINTS

  object PROPERTIES {
    ...
  }
  TOPOLOGY "1" o-- "1" PROPERTIES

  object LINES {
    ...
  }
  TOPOLOGY "1" o-- "1" LINES
@enduml

@startuml rcmdx_measuringsystem_group
  object "//MEASURINGSYSTEM_NAME//" as MEASURINGSYSTEM {
    a:Element (string) = "MEASURINGSYSTEM"
    a:Family (string)
    a:Revision (string)
    a:InstanceVersion (string)
    a:MeasuringMode (Enum) 
  }

  object "//DATASOURCE_NAME//" as DATASOURCE {
    a:Element (string) = "DATASOURCE"
  }
  MEASURINGSYSTEM "1" o-- "1..n" DATASOURCE

  object LOGGING
  MEASURINGSYSTEM "1" o-- "0..1" LOGGING

  object "CONFIGURATION" as ms_config
  MEASURINGSYSTEM "1" o-- "1" ms_config
@enduml

@startuml rcmdx_logging_group
  object LOGGING

  object OUTAGES {
    d:message (string)
    d:systemReference (string)
    d:channelReference (string)
    d:datasourceReference (string)
    d:level (Enum)
  }
  LOGGING "1" o-- "1" OUTAGES
  object "timestamp" as out_timestamp #LightGray {
    data type: Timestamp
  }
  object "duration" as out_duration #LightGray {
    data type: 64 bit integer
  }
  OUTAGES "1" o-- "1" out_timestamp
  OUTAGES "1" o-- "1" out_duration

  object MESSAGES {
    d:message (string)
    d:systemReference (string)
    d:channelReference (string)
    d:level (Enum)
  }
  LOGGING "1" o-- "1" MESSAGES

  object "timestamp" as msg_timestamp #LightGray {
    data type: Timestamp
  }
  MESSAGES "1" o-- "1" msg_timestamp
@enduml

@startuml rcmdx_datasource_group
  object "//DATASOURCE_NAME//" as DATASOURCE {
    a:Element (string) = "DATASOURCE"
  }

  object "timestamp" as ds_timestamp #LightGray {
    data type: Timestamp
  }
  DATASOURCE "1" o-- "1" ds_timestamp

  object "//CHANNEL_NAME//" as CHANNEL {
    a:Element (string) = "CHANNEL"
    ...
  }
  DATASOURCE "1" o-- "1..n" CHANNEL

@enduml

@startuml rcmdx_channel_group
  object "//CHANNEL_NAME//" as CHANNEL {
    a:Element (string) = "CHANNEL"
    a:TriggerMode (Enum)
    a:TriggerValue (64 bit float)
    a:ChannelBasis (Enum)
    a:ChannelType (Enum)
    a:Neighbor (string)
    a:MeasurementUncertainty (32 bit float)
    a:PositionOffset (32 bit float)
  }

  object "data" as channel_data #LightGray
  CHANNEL "1" o-- "0..1" channel_data

  object LIMIT
  CHANNEL "1" o-- "0..1" LIMIT

  object VID {
    ...
  }
  CHANNEL "1" o-- "0..1" VID
  
  object IMG {
    ...
  }
  CHANNEL "1" o-- "0..1" IMG
  
  object sampleindex #LightGray
  CHANNEL "1" o-- "0..1" sampleindex
  
  object coord.CN #LightGray {
    a:Unit (string)
  }
  CHANNEL "1" o-- "0..n" coord.CN

  object data.PRE.MIN.X #LightGray {
    a:Unit (string)
  }
  CHANNEL "1" o-- "0..n" data.PRE.MIN.X

  object data.PRE.MAX.X #LightGray {
    a:Unit (string)
  }
  CHANNEL "1" o-- "0..n" data.PRE.MAX.X

  object data.PRE.AVG.X #LightGray {
    a:Unit (string)
  }
  CHANNEL "1" o-- "0..n" data.PRE.AVG.X

@enduml

@startuml rcmdx_limit_group
  object LIMIT

  object "//LIMIT_NAME//" as limit_name {
    a:Element (string) = "LIMIT"
    a:Priority (8 bit integer)
    a:LimitBound (string)
  }
  
  object limitvalue #LightGray
  limit_name "1" o-- "1" limitvalue

  LIMIT "1" o-- "1..n" limit_name

  object "timestamp" as limit_timestamp #LightGray {
    data type: Timestamp
  }
  limit_name "1" o-- "1" limit_timestamp

  object "duration" as limit_duration #LightGray {
    data type: 64 bit integer
  }
  limit_name "1" o-- "1" limit_duration

@enduml
