' Visit http://plantuml.com/ for more information!

@startuml rcm_dx_Structure

  object RCMDX {
    a:Major (16 bit integer)
    a:Minor (16 bit integer)
  }
 
  object PLATFORM {
    a:Name (Enum)
    a:VehicleNumber (string)
  }
  RCMDX "1" o-- "1" PLATFORM

  object DATAPROCESSING {
    a:Clearance (boolean)
  }
  RCMDX "1" o-- "1" DATAPROCESSING

  object PROCESSINGLOG {
    d:key (string)
    d:value (string)
  }
  DATAPROCESSING "1" o-- "0..1" PROCESSINGLOG

  object CLEARANCEINFORMATION {
    d:key (string)
    d:value (string)
  }
  DATAPROCESSING "1" o-- "0..1" CLEARANCEINFORMATION

  object "CONFIGURATION" as platform_config {
    d:global (string)
    d:network (string)
  }
  PLATFORM "1" o-- "1" platform_config

  object "//SESSION_NAME//" as session_name {
    a:Element (string) = "SESSION"
    a:StartTime (Timestamp)
    a:EndTime (Timestamp)
    a:PositionSource (string)
  } 
  note left: Naming pattern: YYYYMMDD_hhmmss.SSS

  PLATFORM "1" o-- "1" session_name

  object SECTION 

  session_name "1" o-- "1" SECTION

  object SECTIONINFO {
    d:firstTrackOffset (64 bit float)
    d:lastTrackOffset (64 bit float)
    d:startTimestamp (Timestamp)
    d:endTimestamp (Timestamp)
    d:coachOrientation (Enum)
    d:trackInfoOffset (64 bit float)
  }
  SECTION "1" o-- "1" SECTIONINFO

  object TRACKLIST {
    d:id (32 bit signed integer)
    d:startTimestamp (Timestamp)
    d:endTimestamp (Timestamp)
    d:orientation (Enum)
    d:startCoveredDistance (64 bit float)
    d:endCoveredDistance (64 bit float)
  }
  SECTION "1" o-- "1" TRACKLIST
  
  object POSITION {
    d:coveredDistance (64 bit float)
    d:coachOrientation (Enum)
    d:vehicleSpeed (64 bit float) <= Anpassen, TODO!
    d:trackOrientation (Enum)
    d:trackId (32 bit integer)
    d:lineId (32 bit integer)
    d:trackOffset (64 bit integer)
    d:lineKilometer (64 bit float)
    d:positionAccuracy (8 bit integer)
    d:positionQuality (8 bit integer)
    d:timestamp (Timestamp)
  }
  session_name "1" o-- "1" POSITION

  object ENVIRONMENT
  session_name "1" o-- "0..1" ENVIRONMENT

  object "timestamp" as env_timestamp #LightGray {
    data type: Timestamp
  }
  ENVIRONMENT "1" o-- "1" env_timestamp

  object VEHICLESPEED {
    a:Unit (meters per second [m/s])
    d:data (16 bit float)
  }
  ENVIRONMENT "1" o-- "0..1" VEHICLESPEED

  object AMBIENTTEMPERATURE {
    a:Unit (degrees celsius [°C])
    d:data (16 bit float)
  }
  ENVIRONMENT "1" o-- "0..1" AMBIENTTEMPERATURE

  object WINDSPEED {
    a:Unit (meters per second [m/s])
    d:data (16 bit float)
  }
  ENVIRONMENT "1" o-- "0..1" WINDSPEED

  object WINDDIRECTION {
    a:Unit (degree [°])
    d:data (16 bit float)
  }
  ENVIRONMENT "1" o-- "0..1" WINDDIRECTION

  object WEATHERCONDITIONS {
    a:Unit (string)
    d:data (64 bit integer)
  }
  ENVIRONMENT "1" o-- "0..1" WEATHERCONDITIONS


  object "//MEASURINGSYSTEM_NAME//" as MEASURINGSYSTEM {
    a:Element (string) = "MEASURINGSYSTEM"
    a:Family (string)
    a:Revision (string)
    a:InstanceVersion (string)
    a:MeasuringMode (Enum) 
  }

  session_name "1" o-- "1..n" MEASURINGSYSTEM

  object "//DATASOURCE_NAME//" as DATASOURCE {
    a:Element (string) = "DATASOURCE"
  }
  MEASURINGSYSTEM "1" o-- "1..n" DATASOURCE

  object "timestamp" as ds_timestamp #LightGray {
    data type: Timestamp
  }
  DATASOURCE "1" o-- "1" ds_timestamp

  object "//CHANNEL_NAME//" as CHANNEL {
    a:Element (string) = "CHANNEL"
    a:TriggerMode (Enum)
    a:TriggerValue (64 bit float)
    a:ChannelBasis (Enum)
    a:ChannelType (Enum)
    a:Neighbor (string)
    a:MeasurementUncertainty (32 bit float)
    a:PositionOffset (32 bit float)
  }
  DATASOURCE "1" o-- "1..n" CHANNEL

  object "data" as channel_data #LightGray
  CHANNEL "1" o-- "0..1" channel_data

  object LOGGING
  MEASURINGSYSTEM "1" o-- "0..1" LOGGING
  
  object OUTAGES {
    d:message (string)
    d:systemReference (string)
    d:channelReference (string)
    d:datasourceReference (string)
    d:level (Enum)
  }
  LOGGING "1" o-- "1" OUTAGES

  object "timestamp" as out_timestamp #LightGray {
    data type: Timestamp
  }
  object "duration" as out_duration #LightGray {
    data type: 64 bit integer
  }
  OUTAGES "1" o-- "1" out_timestamp
  OUTAGES "1" o-- "1" out_duration

  object MESSAGES {
    d:message (string)
    d:systemReference (string)
    d:channelReference (string)
    d:level (Enum)
  }
  LOGGING "1" o-- "1" MESSAGES

  object "timestamp" as msg_timestamp #LightGray {
    data type: Timestamp
  }
  MESSAGES "1" o-- "1" msg_timestamp

  object TOPOLOGY {
    a:Version (string)
  }

  session_name "1" o-- "1" TOPOLOGY 

  object TRACKS {
    d:id (32bit signed integer)
    d:direction (8bit signed integer)
    d:gtgId (string)
    d:length (32bit float)
    d:name (string)
    d:nrLine (string)
    d:pointFrom (32bit signed integer)
    d:pointTo (32bit signed integer)
    d:switchType (8bit signed integer)
    d:trackType (8bit signed integer)
  }
  TOPOLOGY "1" o-- "1" TRACKS

  object LINES {
    d:id (32bit signed integer)
    d:name (string)
    d:firstStation (string)
    d:lastStation (string)
    d:fromKilometer (32bit float)
    d:toKilometer (32bit float)
  }
  TOPOLOGY "1" o-- "1" LINES

  object SWITCHTRACKS {
    d:gleisstrangId (32bit signed integer)
    d:gleisstrangBez (string)
    d:weicheId (32bit signed integer)
    d:ablenkRichtung (string)
    d:ablenkung (string)
    d:betriebspunkt (string)
    d:herzStueck (string)
    d:minRadius  (32bit float)
    d:nr (32bit signed integer)
    d:zusNr (string)
    d:schienenProfil
    d:status (string)
    d:schienenProfil (string)
    d:schwellenArt (string)
    d:typenPlanNr (32bit signed integer)
    d:typNrZusatz (string)
    d:weichenArt (string)
    d:weichenTyp (string)
    d:weichenForm (string)
    d:weichenZunge (string)
  }
  TOPOLOGY "1" o-- "1" SWITCHTRACKS
  
  object TRACKOBJECTS {
    d:trackId (32bit signed integer)
    d:type (32bit signed integer)
    d:positionStart (32bit float)
    d:positionEnd (32bit float)
    d:extraInfo (string)
  }
  TOPOLOGY "1" o-- "1" TRACKOBJECTS

  object TRACKPOINTS {
    d:trackId (32bit signed integer)
    d:lineId (32bit signed integer)
    d:x (32bit float)
    d:y (32bit float)
    d:z (32bit float)
    d:radius (32bit float)
    d:kilometer (32bit float)
    d:position (32bit float)
    d:cant (32bit float)
    d:inclination (32bit float)
  }
  TOPOLOGY "1" o-- "1" TRACKPOINTS

  object PROPERTIES {
    d:propertyId (32bit signed integer)
    d:name (string)
    d:description.ge (string)
    d:description.fr (string)
    d:description.it (string)
    d:description.en (string)
  }
  TOPOLOGY "1" o-- "1" PROPERTIES

  object EVENT {
    d:systemReference (string)
    d:channelReference (string)
    d:type (string)
  }
  session_name "1" o-- "0..1" EVENT

  object "timestamp" as event_timestamp #LightGray {
    data type: Timestamp
  }

  object "duration" as event_duration #LightGray {
    data type: 64 bit integer
  }

  EVENT "1" o-- "1" event_timestamp
  EVENT "1" o-- "1" event_duration

  object "data" as event_data #LightGray {
    data type: string (XML)
  }
  EVENT "1" o-- "1" event_data

  object RECORD {
    d:type (string)
    d:systemReference (string)
    d:channelReference (string)
  }

  session_name "1" o-- "0..1" RECORD
  object "timestamp" as record_timestamp #LightGray {
    data type: Timestamp
  }
  object "duration" as record_duration #LightGray {
    data type: 64 bit integer
  }

  object "data" as record_data #LightGray {
    data type: string (XML)
  }

  RECORD "1" o-- "1" record_timestamp
  RECORD "1" o-- "1" record_duration
  RECORD "1" o-- "1" record_data

  object "CONFIGURATION" as ms_config
  MEASURINGSYSTEM "1" o-- "1" ms_config

  object "//SETTING_NAME//" as setting_name {
    a:DataType (string)
  }
  ms_config "1" o-- "1" setting_name

  object "timestamp" as setting_timestamp #LightGray {
    data type: Timestamp
  }
  setting_name "1" o-- "1" setting_timestamp

  object "setting" as setting #LightGray {
    data type: string
  }

  setting_name "1" o-- "1" setting

  object LIMIT

  object "//LIMIT_NAME//" as limit_name {
    a:Element (string) = "LIMIT"
    a:Priority (8 bit integer)
    a:LimitBound (string)
  }
  object limitvalue #LightGray

  object VID {
    a:ContentType (MIME-Type, string)
    a:DataTyp (string)
    a:FramesPerSecond (16 bit signed integer)
    a:ResolutionType (Enum)
    a:ResolutionInfoX (32 bit signed integer)
    a:ResolutionInfoY (32 bit signed integer)
  }
  object vid.NNNNNNNNN #LightGray

  object IMG {
    a:ContentType (MIME-Type, string)
    a:DataTyp (string)
    a:ResolutionType (string)
    a:ResolutionvX (32 bit signed integer)
    a:ResolutionInfoY (32 bit signed integer)
  }
  object img.NNNNNNNNN #LightGray

  object sampleindex #LightGray
  
  object coord.CN #LightGray {
    a:Unit (string)
  }

  CHANNEL "1" o-- "0..1" LIMIT
  LIMIT "1" o-- "1..n" limit_name

  object "timestamp" as limit_timestamp #LightGray {
    data type: Timestamp
  }
  object "duration" as limit_duration #LightGray {
    data type: 64 bit integer
  }

  limit_name "1" o-- "1" limit_timestamp
  limit_name "1" o-- "1" limit_duration
  limit_name "1" o-- "1" limitvalue

  CHANNEL "1" o-- "0..1" sampleindex
  CHANNEL "1" o-- "0..n" coord.CN

  CHANNEL "1" o-- "0..1" VID
  CHANNEL "1" o-- "0..1" IMG

  IMG "1" o-- "1..n" img.NNNNNNNNN
  VID "1" o-- "1..n" vid.NNNNNNNNN
  
  object data.PRE.MIN.X #LightGray {
    a:Unit (string)
  }

  object data.PRE.MAX.X #LightGray {
    a:Unit (string)
  }

  object data.PRE.AVG.X #LightGray {
    a:Unit (string)
  }

  CHANNEL "1" o-- "0..n" data.PRE.MIN.X
  CHANNEL "1" o-- "0..n" data.PRE.MAX.X
  CHANNEL "1" o-- "0..n" data.PRE.AVG.X

@enduml