name: Build RCM-DX PDF

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions: {}

jobs:
  make-pdf:
    name: "Build RCM-DX PDF"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # to comment the PDF artifact location in PRs
      artifact-metadata: write # required to upload generated PDF as an artifact
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build Docker image
        run: docker build -t rcm-dx-specification:latest .

      # We use this job to get the version number from the latest release. This
      # is currently only used to automate the definition of the draft version
      # in the PR/Preview build jobs.
      - name: Get latest release
        id: latest-release
        uses: actions/github-script@v9
        with:
          result-encoding: string
          script: |
            var releases  = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            releases = releases.data;
            // Filter out draft and prerelease releases
            releases = releases.filter(x => x.draft != true);
            releases = releases.filter(x => x.prerelease != true);
            if (releases.length) {
              console.log(`Found ${releases[0].tag_name} as the latest release`)
              return releases[0].tag_name;
            } else {
              console.log("No valid releases found");
              return null
            }
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.ref_name == 'main' }}

      # This job is being executed for pull requests to provide a PDF preview
      # and on main after the changes have been merged.
      - name: Build PDF (PR/Preview)
        run: docker run --volume ${{ github.workspace }}:/data --env SPEC_VERSION=${{ steps.latest-release.outputs.result }}-draft --env IS_DRAFT=true rcm-dx-specification:latest
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.ref_name == 'main'}}

      # This job is being executed after a release has been tagged. The built
      # PDF will later on manually be added as an asset to the release.
      - name: Build PDF (Release)
        run: docker run --volume ${{ github.workspace }}:/data --env SPEC_VERSION=${{ github.ref_name }} rcm-dx-specification:latest
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}

      - name: Upload PDF
        id: pdf-upload
        uses: actions/upload-artifact@v7
        with:
          name: RCM-DX-Specification_EN
          path: generated-specs/pdf/RCM-DX-Specification_EN.pdf
          if-no-files-found: error
          archive: false

      - name: Comment with PDF location
        run: |
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} \
            --body "The preview PDF is available at ${{ steps.pdf-upload.outputs.artifact-url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'pull_request' }}
